-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.2
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;sid=FREE;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

CREATE SEQUENCE "mview$_advseq_generic" INCREMENT 1 MINVALUE 1 MAXVALUE 4294967295 START 1 CACHE 50;
CREATE SEQUENCE "mview$_advseq_id" INCREMENT 1 MINVALUE 1 MAXVALUE 4294967295 START 1 CACHE 20;
