-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.2
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;sid=FREE;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;


CREATE TABLE "mview$_adv_temp" (
	"id#" bigint,
	"seq#" bigint,
	text text
) ;
COMMENT ON TABLE "mview$_adv_temp" IS E'Table for temporary data';
CREATE INDEX "mview$_adv_temp_id#_seq#" ON "mview$_adv_temp" ("id#", "seq#");

CREATE TABLE "mview$_adv_info" (
	"runid#" bigint NOT NULL,
	"seq#" bigint NOT NULL,
	type bigint NOT NULL,
	infolen bigint NOT NULL,
	info bytea,
	status bigint,
	flag bigint
) ;
COMMENT ON TABLE "mview$_adv_info" IS E'Internal table for passing information from the SQL analyzer';
CREATE UNIQUE INDEX "mview$_adv_info_runid#_seq#" ON "mview$_adv_info" ("runid#", "seq#");
ALTER TABLE "mview$_adv_info" ADD PRIMARY KEY ("runid#","seq#");

CREATE TABLE "mview$_adv_level" (
	"runid#" bigint NOT NULL,
	"levelid#" bigint NOT NULL,
	"dimobj#" bigint,
	flags bigint NOT NULL,
	"tblobj#" bigint NOT NULL,
	columnlist bytea NOT NULL,
	levelname varchar(128)
) ;
COMMENT ON TABLE "mview$_adv_level" IS E'Level definition';
CREATE UNIQUE INDEX "mview$_adv_level_runid#_levelid#" ON "mview$_adv_level" ("runid#", "levelid#");
ALTER TABLE "mview$_adv_level" ADD PRIMARY KEY ("runid#","levelid#");

CREATE TABLE "mview$_adv_exceptions" (
	"runid#" bigint,
	owner varchar(128),
	table_name varchar(128),
	dimension_name varchar(128),
	relationship varchar(11),
	bad_rowid oid
) ;
COMMENT ON TABLE "mview$_adv_exceptions" IS E'Output table for dimension validations';

CREATE TABLE "mview$_adv_parameters" (
	parameter_name varchar(128) NOT NULL,
	parameter_type bigint NOT NULL,
	string_value varchar(30),
	date_value timestamp,
	numerical_value bigint
) ;
COMMENT ON TABLE "mview$_adv_parameters" IS E'Summary advisor tuning parameters';
ALTER TABLE "mview$_adv_parameters" ADD PRIMARY KEY (parameter_name);

CREATE TABLE "mview$_adv_filterinstance" (
	"runid#" bigint NOT NULL,
	"filterid#" bigint,
	"subfilternum#" bigint,
	subfiltertype bigint,
	str_value varchar(1028),
	num_value1 bigint,
	num_value2 bigint,
	date_value1 timestamp,
	date_value2 timestamp
) ;
COMMENT ON TABLE "mview$_adv_filterinstance" IS E'Table for workload filter instance definition';

CREATE TABLE "mview$_adv_fjg" (
	"fjgid#" bigint NOT NULL,
	"ajgid#" bigint NOT NULL,
	fjgdeslen bigint NOT NULL,
	fjgdes bytea NOT NULL,
	hashvalue bigint NOT NULL,
	frequency bigint
) ;
COMMENT ON TABLE "mview$_adv_fjg" IS E'Representation for query join sub-graph not in AJG ';
ALTER TABLE "mview$_adv_fjg" ADD PRIMARY KEY ("fjgid#");

CREATE TABLE "mview$_adv_ajg" (
	"ajgid#" bigint NOT NULL,
	"runid#" bigint NOT NULL,
	ajgdeslen bigint NOT NULL,
	ajgdes bytea NOT NULL,
	hashvalue bigint NOT NULL,
	frequency bigint
) ;
COMMENT ON TABLE "mview$_adv_ajg" IS E'Anchor-join graph representation';
ALTER TABLE "mview$_adv_ajg" ADD PRIMARY KEY ("ajgid#");

CREATE TABLE "mview$_adv_log" (
	"runid#" bigint NOT NULL,
	"filterid#" bigint,
	run_begin timestamp,
	run_end timestamp,
	run_type bigint,
	uname varchar(128),
	status bigint NOT NULL,
	message varchar(2000),
	completed bigint,
	total bigint,
	error_code varchar(20)
) ;
COMMENT ON TABLE "mview$_adv_log" IS E'Log all calls to summary advisory functions';
ALTER TABLE "mview$_adv_log" ADD PRIMARY KEY ("runid#");

CREATE TABLE "mview$_adv_sqldepend" (
	"collectionid#" bigint,
	inst_id bigint,
	from_address bytea,
	from_hash bigint,
	to_owner varchar(128),
	to_name varchar(1000),
	to_type bigint,
	cardinality bigint
) ;
COMMENT ON TABLE "mview$_adv_sqldepend" IS E'Temporary table for workload collections';
CREATE INDEX "mview$_adv_sqldepend_collectionid#_from_address_from_hash_inst_" ON "mview$_adv_sqldepend" ("collectionid#", from_address, from_hash, inst_id);

CREATE TABLE sqlplus_product_profile (
	product varchar(30) NOT NULL,
	userid varchar(128),
	attribute varchar(240),
	scope varchar(240),
	numeric_value decimal(15,2),
	char_value varchar(240),
	date_value timestamp,
	long_value text
) ;

CREATE TABLE scheduler_job_args_tbl (
	owner varchar(128),
	job_name varchar(128),
	argument_name varchar(128),
	argument_position bigint,
	argument_type varchar(257),
	value varchar(4000),
	anydata_value ANYDATA,
	out_argument varchar(5)
) ;

CREATE TABLE scheduler_program_args_tbl (
	owner varchar(128) NOT NULL,
	program_name varchar(128) NOT NULL,
	argument_name varchar(128),
	argument_position bigint NOT NULL,
	argument_type varchar(257),
	metadata_attribute varchar(19),
	default_value varchar(4000),
	default_anydata_value ANYDATA,
	out_argument varchar(5)
) ;

CREATE TABLE help (
	topic varchar(50) NOT NULL,
	seq bigint NOT NULL,
	info varchar(80)
) ;
ALTER TABLE help ADD PRIMARY KEY (topic,seq);

CREATE TABLE "mview$_adv_basetable" (
	"collectionid#" bigint NOT NULL,
	"queryid#" bigint NOT NULL,
	owner varchar(128),
	table_name varchar(128),
	table_type bigint
) ;
COMMENT ON TABLE "mview$_adv_basetable" IS E'Base tables refered by a query';
CREATE INDEX "mview$_adv_basetable_queryid#" ON "mview$_adv_basetable" ("queryid#");

CREATE TABLE "mview$_adv_output" (
	"runid#" bigint NOT NULL,
	output_type bigint NOT NULL,
	"rank#" bigint NOT NULL,
	action_type varchar(6),
	summary_owner varchar(128),
	summary_name varchar(128),
	group_by_columns varchar(2000),
	where_clause varchar(2000),
	from_clause varchar(2000),
	measures_list varchar(2000),
	fact_tables varchar(1000),
	grouping_levels varchar(2000),
	querylen bigint,
	query_text text,
	storage_in_bytes bigint,
	pct_performance_gain bigint,
	frequency bigint,
	cumulative_benefit bigint,
	benefit_to_cost_ratio bigint NOT NULL,
	validated bigint
) ;
COMMENT ON TABLE "mview$_adv_output" IS E'Output table for summary recommendations and evaluations';
CREATE UNIQUE INDEX "mview$_adv_output_runid#_rank#" ON "mview$_adv_output" ("runid#", "rank#");
ALTER TABLE "mview$_adv_output" ADD PRIMARY KEY ("runid#","rank#");

CREATE TABLE "mview$_adv_workload" (
	"queryid#" bigint NOT NULL,
	"collectionid#" bigint NOT NULL,
	collecttime timestamp NOT NULL,
	application varchar(128),
	cardinality bigint,
	resultsize bigint,
	uname varchar(128) NOT NULL,
	qdate timestamp,
	priority bigint,
	exec_time bigint,
	sql_text text NOT NULL,
	sql_textlen bigint NOT NULL,
	sql_hash bigint,
	sql_addr bytea,
	frequency bigint
) ;
COMMENT ON TABLE "mview$_adv_workload" IS E'Shared workload repository for DBA users of summary advisor';
CREATE INDEX "mview$_adv_workload_collectionid#_queryid#" ON "mview$_adv_workload" ("collectionid#", "queryid#");
ALTER TABLE "mview$_adv_workload" ADD PRIMARY KEY ("queryid#");

CREATE TABLE "mview$_adv_gc" (
	"gcid#" bigint NOT NULL,
	"fjgid#" bigint NOT NULL,
	gcdeslen bigint NOT NULL,
	gcdes bytea NOT NULL,
	hashvalue bigint NOT NULL,
	frequency bigint
) ;
COMMENT ON TABLE "mview$_adv_gc" IS E'Group-by columns of a query';
ALTER TABLE "mview$_adv_gc" ADD PRIMARY KEY ("gcid#");

CREATE TABLE "mview$_adv_journal" (
	"runid#" bigint NOT NULL,
	"seq#" bigint NOT NULL,
	timestamp timestamp NOT NULL,
	flags bigint NOT NULL,
	num bigint,
	text text,
	textlen bigint
) ;
COMMENT ON TABLE "mview$_adv_journal" IS E'Summary advisor journal table for debugging and information';
CREATE UNIQUE INDEX "mview$_adv_journal_runid#_seq#" ON "mview$_adv_journal" ("runid#", "seq#");
ALTER TABLE "mview$_adv_journal" ADD PRIMARY KEY ("runid#","seq#");

CREATE TABLE "mview$_adv_plan" (
	statement_id varchar(30),
	timestamp timestamp,
	remarks varchar(80),
	operation varchar(30),
	options varchar(255),
	object_node varchar(128),
	object_owner varchar(128),
	object_name varchar(128),
	object_instance numeric(38),
	object_type varchar(30),
	optimizer varchar(255),
	search_columns bigint,
	id numeric(38),
	parent_id numeric(38),
	position numeric(38),
	cost numeric(38),
	cardinality numeric(38),
	bytes numeric(38),
	other_tag varchar(255),
	partition_start varchar(255),
	partition_stop varchar(255),
	partition_id numeric(38),
	other text,
	distribution varchar(30),
	cpu_cost numeric(38),
	io_cost numeric(38),
	temp_space numeric(38)
) ;
COMMENT ON TABLE "mview$_adv_plan" IS E'Private plan table for estimate_mview_size operations';

CREATE TABLE "mview$_adv_pretty" (
	"queryid#" bigint,
	sql_text text
) ;
COMMENT ON TABLE "mview$_adv_pretty" IS E'Table for sql parsing';
CREATE INDEX "mview$_adv_pretty_queryid#" ON "mview$_adv_pretty" ("queryid#");

CREATE TABLE "mview$_adv_clique" (
	"cliqueid#" bigint NOT NULL,
	"runid#" bigint NOT NULL,
	cliquedeslen bigint NOT NULL,
	cliquedes bytea NOT NULL,
	hashvalue bigint NOT NULL,
	frequency bigint NOT NULL,
	bytecost bigint NOT NULL,
	rowsize bigint NOT NULL,
	numrows bigint NOT NULL
) ;
COMMENT ON TABLE "mview$_adv_clique" IS E'Table for storing canonical form of Clique queries';
ALTER TABLE "mview$_adv_clique" ADD PRIMARY KEY ("cliqueid#");

CREATE TABLE redo_db (
	dbid bigint NOT NULL,
	global_dbname varchar(129),
	dbuname varchar(32),
	version varchar(32),
	"thread#" bigint NOT NULL,
	resetlogs_scn_bas bigint,
	resetlogs_scn_wrp bigint,
	resetlogs_time bigint NOT NULL,
	presetlogs_scn_bas bigint,
	presetlogs_scn_wrp bigint,
	presetlogs_time bigint NOT NULL,
	seqno_rcv_cur bigint,
	seqno_rcv_lo bigint,
	seqno_rcv_hi bigint,
	seqno_done_cur bigint,
	seqno_done_lo bigint,
	seqno_done_hi bigint,
	gap_seqno bigint,
	gap_ret bigint,
	gap_done bigint,
	apply_seqno bigint,
	apply_done bigint,
	purge_done bigint,
	has_child bigint,
	error1 bigint,
	status bigint,
	create_date timestamp,
	ts1 bigint,
	ts2 bigint,
	gap_next_scn bigint,
	gap_next_time bigint,
	curscn_time bigint,
	resetlogs_scn bigint NOT NULL,
	presetlogs_scn bigint NOT NULL,
	gap_ret2 bigint,
	curlog bigint,
	endian bigint,
	enqidx bigint,
	spare4 bigint,
	spare5 timestamp,
	spare6 varchar(65),
	spare7 varchar(129),
	ts3 bigint,
	curblkno bigint,
	spare8 bigint,
	spare9 bigint,
	spare10 bigint,
	spare11 bigint,
	spare12 bigint,
	tenant_key bigint NOT NULL
) ;
CREATE INDEX "redo_db_tenant_key_dbid_thread#_resetlogs_scn_resetlogs_time" ON redo_db (tenant_key, dbid, "thread#", resetlogs_scn, resetlogs_time);

CREATE TABLE "mview$_adv_rollup" (
	"runid#" bigint NOT NULL,
	"clevelid#" bigint NOT NULL,
	"plevelid#" bigint NOT NULL,
	flags bigint NOT NULL
) ;
COMMENT ON TABLE "mview$_adv_rollup" IS E'Each row repesents either a functional dependency or join-key relationship';
CREATE UNIQUE INDEX "mview$_adv_rollup_runid#_clevelid#_plevelid#" ON "mview$_adv_rollup" ("runid#", "clevelid#", "plevelid#");
ALTER TABLE "mview$_adv_rollup" ADD PRIMARY KEY ("runid#","clevelid#","plevelid#");

CREATE TABLE "mview$_adv_filter" (
	"filterid#" bigint NOT NULL,
	"subfilternum#" bigint NOT NULL,
	subfiltertype bigint NOT NULL,
	str_value varchar(1028),
	num_value1 bigint,
	num_value2 bigint,
	date_value1 timestamp,
	date_value2 timestamp
) ;
COMMENT ON TABLE "mview$_adv_filter" IS E'Table for workload filter definition';
CREATE UNIQUE INDEX "mview$_adv_filter_filterid#_subfilternum#" ON "mview$_adv_filter" ("filterid#", "subfilternum#");
ALTER TABLE "mview$_adv_filter" ADD PRIMARY KEY ("filterid#","subfilternum#");

CREATE TABLE "mview$_adv_eligible" (
	"sumobjn#" bigint NOT NULL,
	"runid#" bigint NOT NULL,
	bytecost bigint NOT NULL,
	flags bigint NOT NULL,
	frequency bigint NOT NULL
) ;
COMMENT ON TABLE "mview$_adv_eligible" IS E'Summary management rewrite eligibility information';
CREATE UNIQUE INDEX "mview$_adv_eligible_sumobjn#_runid#" ON "mview$_adv_eligible" ("sumobjn#", "runid#");
ALTER TABLE "mview$_adv_eligible" ADD PRIMARY KEY ("sumobjn#","runid#");

CREATE TABLE redo_log (
	dbid bigint NOT NULL,
	global_dbname varchar(129),
	dbuname varchar(32),
	version varchar(32),
	"thread#" bigint NOT NULL,
	resetlogs_scn_bas bigint,
	resetlogs_scn_wrp bigint,
	resetlogs_time bigint NOT NULL,
	presetlogs_scn_bas bigint,
	presetlogs_scn_wrp bigint,
	presetlogs_time bigint NOT NULL,
	"sequence#" bigint NOT NULL,
	dupid bigint,
	status1 bigint,
	status2 bigint,
	create_time varchar(32),
	close_time varchar(32),
	done_time varchar(32),
	first_scn_bas bigint,
	first_scn_wrp bigint,
	first_time bigint,
	next_scn_bas bigint,
	next_scn_wrp bigint,
	next_time bigint,
	first_scn bigint,
	next_scn bigint,
	resetlogs_scn bigint NOT NULL,
	blocks bigint,
	block_size bigint,
	old_blocks bigint,
	create_date timestamp,
	error1 bigint,
	error2 bigint,
	filename varchar(513),
	ts1 bigint,
	ts2 bigint,
	endian bigint,
	spare2 bigint,
	spare3 bigint,
	spare4 bigint,
	spare5 timestamp,
	spare6 varchar(65),
	spare7 varchar(129),
	ts3 bigint,
	presetlogs_scn bigint NOT NULL,
	spare8 bigint,
	spare9 bigint,
	spare10 bigint,
	old_status1 bigint,
	old_status2 bigint,
	old_filename varchar(513),
	tenant_key bigint NOT NULL
) ;
CREATE INDEX "redo_log_tenant_key_dbid_thread#_resetlogs_scn_resetlogs_time" ON redo_log (tenant_key, dbid, "thread#", resetlogs_scn, resetlogs_time);
ALTER TABLE "mview$_adv_info" ADD CONSTRAINT "mview$_adv_info_fk" FOREIGN KEY ("runid#") REFERENCES "mview$_adv_log"("runid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mview$_adv_level" ADD CONSTRAINT "mview$_adv_level_fk" FOREIGN KEY ("runid#") REFERENCES "mview$_adv_log"("runid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mview$_adv_exceptions" ADD CONSTRAINT "mview$_adv_exception_fk" FOREIGN KEY ("runid#") REFERENCES "mview$_adv_log"("runid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mview$_adv_filterinstance" ADD CONSTRAINT "mview$_adv_filterinstance_fk" FOREIGN KEY ("runid#") REFERENCES "mview$_adv_log"("runid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mview$_adv_fjg" ADD CONSTRAINT "mview$_adv_fjg_fk" FOREIGN KEY ("ajgid#") REFERENCES "mview$_adv_ajg"("ajgid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mview$_adv_ajg" ADD CONSTRAINT "mview$_adv_ajg_fk" FOREIGN KEY ("runid#") REFERENCES "mview$_adv_log"("runid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mview$_adv_basetable" ADD CONSTRAINT "mview$_adv_basetable_fk" FOREIGN KEY ("queryid#") REFERENCES "mview$_adv_workload"("queryid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mview$_adv_output" ADD CONSTRAINT "mview$_adv_output_fk" FOREIGN KEY ("runid#") REFERENCES "mview$_adv_log"("runid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mview$_adv_gc" ADD CONSTRAINT "mview$_adv_gc_fk" FOREIGN KEY ("fjgid#") REFERENCES "mview$_adv_fjg"("fjgid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mview$_adv_journal" ADD CONSTRAINT "mview$_adv_journal_fk" FOREIGN KEY ("runid#") REFERENCES "mview$_adv_log"("runid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mview$_adv_clique" ADD CONSTRAINT "mview$_adv_clique_fk" FOREIGN KEY ("runid#") REFERENCES "mview$_adv_log"("runid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mview$_adv_rollup" ADD CONSTRAINT "mview$_adv_rollup_cfk" FOREIGN KEY ("runid#","clevelid#") REFERENCES "mview$_adv_level"("runid#","levelid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mview$_adv_rollup" ADD CONSTRAINT "mview$_adv_rollup_pfk" FOREIGN KEY ("runid#","plevelid#") REFERENCES "mview$_adv_level"("runid#","levelid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mview$_adv_rollup" ADD CONSTRAINT "mview$_adv_rollup_fk" FOREIGN KEY ("runid#") REFERENCES "mview$_adv_log"("runid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "mview$_adv_eligible" ADD CONSTRAINT "mview$_adv_eligible_fk" FOREIGN KEY ("runid#") REFERENCES "mview$_adv_log"("runid#") ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
