-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.2
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;sid=FREE;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

CREATE OR REPLACE VIEW scheduler_job_args (owner, job_name, argument_name, argument_position, argument_type, value, anydata_value, out_argument) AS SELECT  "OWNER","JOB_NAME","ARGUMENT_NAME","ARGUMENT_POSITION","ARGUMENT_TYPE","VALUE","ANYDATA_VALUE","OUT_ARGUMENT"  FROM sys.all_scheduler_job_args;

CREATE OR REPLACE VIEW mview_filter (filterid, subfilternum, subfiltertype, str_value, num_value1, num_value2, date_value1, date_value2) AS SELECT 
      a.filterid# as filterid,
      a.subfilternum# as subfilternum,
      CASE WHEN a.subfiltertype=1 THEN 'APPLICATION' WHEN a.subfiltertype=2 THEN 'CARDINALITY' WHEN a.subfiltertype=3 THEN 'LASTUSE' WHEN a.subfiltertype=4 THEN 'FREQUENCY' WHEN a.subfiltertype=5 THEN 'USER' WHEN a.subfiltertype=6 THEN 'PRIORITY' WHEN a.subfiltertype=7 THEN 'BASETABLE' WHEN a.subfiltertype=8 THEN 'RESPONSETIME' WHEN a.subfiltertype=9 THEN 'COLLECTIONID' WHEN a.subfiltertype=10 THEN 'TRACENAME' WHEN a.subfiltertype=11 THEN 'SCHEMA'  ELSE 'UNKNOWN' END  AS subfiltertype,
      a.str_value,
      (CASE WHEN a.num_value1=-999 THEN NULL  ELSE a.num_value1 END )::numeric  AS num_value1,
      (CASE WHEN a.num_value2=-999 THEN NULL  ELSE a.num_value2 END )::numeric  AS num_value2,
      a.date_value1,
      a.date_value2
    FROM system.mview$_adv_filter a, system.mview$_adv_log b, SYS.ALL_USERS u
   WHERE a.filterid# = b.runid#
   AND b.uname = u.username
   AND u.user_id = userenv('SCHEMAID');

COMMENT ON VIEW mview_filter  IS E'Workload filter records';

CREATE OR REPLACE VIEW scheduler_program_args (owner, program_name, argument_name, argument_position, argument_type, metadata_attribute, default_value, default_anydata_value, out_argument) AS SELECT  "OWNER","PROGRAM_NAME","ARGUMENT_NAME","ARGUMENT_POSITION","ARGUMENT_TYPE","METADATA_ATTRIBUTE","DEFAULT_VALUE","DEFAULT_ANYDATA_VALUE","OUT_ARGUMENT"  FROM sys.all_scheduler_program_args;

CREATE OR REPLACE VIEW mview_workload (workloadid, import_time, queryid, application, cardinality, resultsize, lastuse, frequency, owner, priority, query, responsetime) AS SELECT 
  A.collectionid# as workloadid,
  A.collecttime as import_time,
  A.queryid# as queryid,
  A.application,
  A.cardinality,
  A.resultsize,
  A.qdate as lastuse,
  A.frequency,
  A.uname as owner,
  A.priority,
  A.sql_text as query,
  A.exec_time as responsetime
 FROM SYSTEM.MVIEW$_ADV_WORKLOAD A, SYSTEM.MVIEW$_ADV_LOG B, SYS.ALL_USERS D
WHERE A.collectionid# = B.runid#
AND B.uname = D.username
AND D.user_id = userenv('SCHEMAID');

COMMENT ON VIEW mview_workload  IS E'This view gives DBA access to shared workload';

CREATE OR REPLACE VIEW product_privs (product, userid, attribute, scope, numeric_value, char_value, date_value, long_value) AS SELECT  PRODUCT, USERID, ATTRIBUTE, SCOPE,
         NUMERIC_VALUE, CHAR_VALUE, DATE_VALUE, LONG_VALUE
   FROM SQLPLUS_PRODUCT_PROFILE
  WHERE USERID = 'PUBLIC' OR
        USERID LIKE SYS_CONTEXT('USERENV','CURRENT_USER');

CREATE OR REPLACE VIEW mview_log (id, filterid, run_begin, run_end, type, status, message, completed, total, error_code) AS SELECT 
      m.runid# as id,
      m.filterid# as filterid,
      m.run_begin,
      m.run_end,
      CASE WHEN m.run_type=1 THEN 'EVALUATE' WHEN m.run_type=2 THEN 'EVALUATE_W' WHEN m.run_type=3 THEN 'RECOMMEND' WHEN m.run_type=4 THEN 'RECOMMEND_W' WHEN m.run_type=5 THEN 'VALIDATE' WHEN m.run_type=6 THEN 'WORKLOAD' WHEN m.run_type=7 THEN 'FILTER'  ELSE 'UNKNOWN' END  AS type,
      CASE WHEN m.status=0 THEN 'UNUSED' WHEN m.status=1 THEN 'CANCELLED' WHEN m.status=2 THEN 'IN_PROGRESS' WHEN m.status=3 THEN 'COMPLETED' WHEN m.status=4 THEN 'ERROR'  ELSE 'UNKNOWN' END  AS status,
      m.message,
      m.completed,
      m.total,
      m.error_code
    FROM system.mview$_adv_log m, sys.all_users u
   where m.uname = u.username
   and   u.user_id = userenv('SCHEMAID');

COMMENT ON VIEW mview_log  IS E'Advisor session log';

CREATE OR REPLACE VIEW mview_exceptions (runid, owner, table_name, dimension_name, relationship, bad_rowid) AS SELECT 
  t1.runid# as runid,
  owner,
  table_name,
  dimension_name,
  relationship,
  bad_rowid
 FROM SYSTEM.MVIEW$_ADV_EXCEPTIONS t1, SYSTEM.MVIEW$_ADV_LOG t2, SYS.ALL_USERS u
where
  t1.runid# = t2.runid# and
  u.username = t2.uname and
  u.user_id = userenv('SCHEMAID');

COMMENT ON VIEW mview_exceptions  IS E'This view gives DBA access to dimension validation results';

CREATE OR REPLACE VIEW mview_filterinstance (runid, filterid, subfilternum, subfiltertype, str_value, num_value1, num_value2, date_value1, date_value2) AS SELECT 
      a.runid# as runid,
      a.filterid# as filterid,
      a.subfilternum# as subfilternum,
      CASE WHEN a.subfiltertype=1 THEN 'APPLICATION' WHEN a.subfiltertype=2 THEN 'CARDINALITY' WHEN a.subfiltertype=3 THEN 'LASTUSE' WHEN a.subfiltertype=4 THEN 'FREQUENCY' WHEN a.subfiltertype=5 THEN 'USER' WHEN a.subfiltertype=6 THEN 'PRIORITY' WHEN a.subfiltertype=7 THEN 'BASETABLE' WHEN a.subfiltertype=8 THEN 'RESPONSETIME' WHEN a.subfiltertype=9 THEN 'COLLECTIONID' WHEN a.subfiltertype=10 THEN 'TRACENAME' WHEN a.subfiltertype=11 THEN 'SCHEMA'  ELSE 'UNKNOWN' END  AS subfiltertype,
      a.str_value,
      (CASE WHEN a.num_value1=-999 THEN NULL  ELSE a.num_value1 END )::numeric  AS num_value1,
      (CASE WHEN a.num_value2=-999 THEN NULL  ELSE a.num_value2 END )::numeric  AS num_value2,
      a.date_value1,
      a.date_value2
    FROM system.mview$_adv_filterinstance a;

COMMENT ON VIEW mview_filterinstance  IS E'Workload filter instance records';

CREATE OR REPLACE VIEW mview_recommendations (runid, all_tables, fact_tables, grouping_levels, query_text, recommendation_number, recommended_action, mview_owner, mview_name, storage_in_bytes, pct_performance_gain, benefit_to_cost_ratio) AS SELECT 
  t1.runid# as runid,
  t1.from_clause as all_tables,
  fact_tables,
  grouping_levels,
  query_text,
  rank# as recommendation_number,
  action_type as recommended_action,
  summary_owner as mview_owner,
  summary_name as mview_name,
  storage_in_bytes,
  pct_performance_gain,
  benefit_to_cost_ratio
 FROM SYSTEM.MVIEW$_ADV_OUTPUT t1, SYSTEM.MVIEW$_ADV_LOG t2, SYS.ALL_USERS u
where
  t1.runid# = t2.runid# and
  u.username = t2.uname and
  u.user_id = userenv('SCHEMAID') and
  t1.output_type = 0
order by t1.rank#;

COMMENT ON VIEW mview_recommendations  IS E'This view gives DBA access to summary recommendations';

CREATE OR REPLACE VIEW mview_evaluations (runid, mview_owner, mview_name, rank, storage_in_bytes, frequency, cumulative_benefit, benefit_to_cost_ratio) AS SELECT 
  t1.runid# as runid,
  summary_owner AS mview_owner,
  summary_name AS mview_name,
  rank# as rank,
  storage_in_bytes,
  frequency,
  cumulative_benefit,
  benefit_to_cost_ratio
 FROM SYSTEM.MVIEW$_ADV_OUTPUT t1, SYSTEM.MVIEW$_ADV_LOG t2, SYS.ALL_USERS u
where
  t1.runid# = t2.runid# and
  u.username = t2.uname and
  u.user_id = userenv('SCHEMAID') and
  t1.output_type = 1
order by t1.rank#;

COMMENT ON VIEW mview_evaluations  IS E'This view gives DBA access to summary evaluation output';


