-- Generated by Ora2Pg, the Oracle database Schema converter, version 18.2
-- Copyright 2000-2017 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=oracle;sid=FREE;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;

CREATE USER SYSTEM WITH PASSWORD 'change_my_secret' LOGIN;
CREATE ROLE SELECT_CATALOG_ROLE;

-- Set priviledge on TABLE SCHEDULER_JOB_ARGS_TBL
ALTER TABLE scheduler_job_args_tbl OWNER TO system;
GRANT ALL ON  scheduler_job_args_tbl TO system;
REVOKE ALL ON scheduler_job_args_tbl FROM PUBLIC;
GRANT SELECT ON scheduler_job_args_tbl TO select_catalog_role;

-- Set priviledge on TABLE SCHEDULER_PROGRAM_ARGS_TBL
ALTER TABLE scheduler_program_args_tbl OWNER TO system;
GRANT ALL ON  scheduler_program_args_tbl TO system;
REVOKE ALL ON scheduler_program_args_tbl FROM PUBLIC;
GRANT SELECT ON scheduler_program_args_tbl TO select_catalog_role;

-- Set priviledge on VIEW SCHEDULER_JOB_ARGS
ALTER VIEW scheduler_job_args OWNER TO system;
GRANT ALL ON  scheduler_job_args TO system;
REVOKE ALL ON scheduler_job_args FROM PUBLIC;
GRANT SELECT ON scheduler_job_args TO select_catalog_role;

-- Set priviledge on VIEW SCHEDULER_PROGRAM_ARGS
ALTER VIEW scheduler_program_args OWNER TO system;
GRANT ALL ON  scheduler_program_args TO system;
REVOKE ALL ON scheduler_program_args FROM PUBLIC;
GRANT SELECT ON scheduler_program_args TO select_catalog_role;


